/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package my.project;
import java.sql.*; 
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jfree.data.category.DefaultCategoryDataset; 
import org.jfree.chart.ChartFactory; 
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.JFreeChart; 
import org.jfree.chart.ChartUtilities; 
/**
 *
 * @author DELL
 */
public class BarChartJDBCExample extends javax.swing.JFrame {
Statement statement=null;
    Connection connect=null;
    //private Number unit_sale;
    /** Creates new form BarChartJDBCExample */
    public BarChartJDBCExample() throws ClassNotFoundException, SQLException {
        initComponents();
        sysConnect();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void sysConnect() throws ClassNotFoundException, SQLException{
    Class.forName( "com.mysql.cj.jdbc.Driver" );
      connect = DriverManager.getConnection( "jdbc:mysql://localhost:3306/river_mini?autoReconnect=true&useSSL=false","root","1234");
      
     DefaultCategoryDataset my_bar_chart_dataset = new DefaultCategoryDataset();
                statement = connect.createStatement();
                try {
                        ResultSet query_set = statement.executeQuery("select ");
                        while (query_set.next()) {
                                String category = query_set.getString("mobile_brand");
                                int marks = query_set.getInt("unit_sale");
                                my_bar_chart_dataset.addValue(marks,"sale",category);
                                }
                JFreeChart BarChartObject=ChartFactory.createBarChart("Bar Chart","mobile_brand","unit_sale",my_bar_chart_dataset,PlotOrientation.VERTICAL,true,true,false);                  
                query_set.close();
                statement.close(); 
                connect.close();
                int width=640; /* Width of the image */
                int height=480; /* Height of the image */                
                File BarChart=new File("output_chart.png");              
                ChartUtilities.saveChartAsPNG(BarChart,BarChartObject,width,height); 
                }
                 catch (Exception i)
                 {
            System.out.println(i);
                 }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BarChartJDBCExample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BarChartJDBCExample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BarChartJDBCExample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BarChartJDBCExample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new BarChartJDBCExample().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(BarChartJDBCExample.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(BarChartJDBCExample.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
